service: apollo-lambda
provider:
  name: aws
  runtime: nodejs16.x
  httpApi:
    cors: true
  environment:
    SQL_HOST: ${ssm:/dev/grover/sql_host}
    SQL_USER: ${ssm:/dev/grover/sql_user}
    SQL_PASS: ${ssm:/dev/grover/sql_pass}
    SQL_DB: ${ssm:/dev/grover/sql_db}
functions:
  graphql:
    # Make sure your file path is correct!
    # (e.g., if your file is in the root folder use server.graphqlHandler )
    # The format is: <FILENAME>.<HANDLER>
    handler: src/server.graphqlHandler # highlight-line
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
# Omit the following lines if you aren't using TS!
plugins:
  - serverless-plugin-typescript
package:
  patterns:
  - src/*.graphql
